# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screencropper_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.fondo = QtWidgets.QLabel(Form)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.fondo.setObjectName("fondo")
        self.frente = QtWidgets.QLabel(Form)
        self.frente.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.frente.setObjectName("frente")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1742, 735, 161, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.min_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_button.sizePolicy().hasHeightForWidth())
        self.min_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.min_button.setFont(font)
        self.min_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"}")
        self.min_button.setObjectName("min_button")
        self.horizontalLayout_2.addWidget(self.min_button)
        self.config_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_button.sizePolicy().hasHeightForWidth())
        self.config_button.setSizePolicy(sizePolicy)
        self.config_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.config_button.setFont(font)
        self.config_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"}")
        self.config_button.setObjectName("config_button")
        self.horizontalLayout_2.addWidget(self.config_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_2.addWidget(self.exit_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.answer_pencil_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_pencil_button.sizePolicy().hasHeightForWidth())
        self.answer_pencil_button.setSizePolicy(sizePolicy)
        self.answer_pencil_button.setMaximumSize(QtCore.QSize(10000, 30000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.answer_pencil_button.setFont(font)
        self.answer_pencil_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.answer_pencil_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"}")
        self.answer_pencil_button.setObjectName("answer_pencil_button")
        self.verticalLayout.addWidget(self.answer_pencil_button)
        self.borrador_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borrador_button.sizePolicy().hasHeightForWidth())
        self.borrador_button.setSizePolicy(sizePolicy)
        self.borrador_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.borrador_button.setFont(font)
        self.borrador_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.borrador_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"\n"
"}")
        self.borrador_button.setObjectName("borrador_button")
        self.verticalLayout.addWidget(self.borrador_button)
        self.rect_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rect_button.sizePolicy().hasHeightForWidth())
        self.rect_button.setSizePolicy(sizePolicy)
        self.rect_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rect_button.setFont(font)
        self.rect_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rect_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(85, 170, 127);\n"
"}\n"
"")
        self.rect_button.setObjectName("rect_button")
        self.verticalLayout.addWidget(self.rect_button)
        self.enter_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enter_button.sizePolicy().hasHeightForWidth())
        self.enter_button.setSizePolicy(sizePolicy)
        self.enter_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.enter_button.setFont(font)
        self.enter_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(255, 176, 17);\n"
"}\n"
"")
        self.enter_button.setObjectName("enter_button")
        self.verticalLayout.addWidget(self.enter_button)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1740, 730, 166, 270))
        self.label.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10%;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.fondo.raise_()
        self.frente.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fondo.setText(_translate("Form", "TextLabel"))
        self.frente.setText(_translate("Form", "TextLabel"))
        self.min_button.setText(_translate("Form", "-"))
        self.config_button.setText(_translate("Form", "o"))
        self.exit_button.setText(_translate("Form", "x"))
        self.answer_pencil_button.setText(_translate("Form", "answers pencil"))
        self.borrador_button.setText(_translate("Form", "borrador pencil"))
        self.rect_button.setText(_translate("Form", "rect"))
        self.enter_button.setText(_translate("Form", "enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
