# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(148, 108)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(6, 20, 131, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_pregunta = QtWidgets.QPushButton(self.widget)
        self.boton_pregunta.setObjectName("boton_pregunta")
        self.horizontalLayout.addWidget(self.boton_pregunta)
        self.ok_pregunta = QtWidgets.QPushButton(self.widget)
        self.ok_pregunta.setObjectName("ok_pregunta")
        self.horizontalLayout.addWidget(self.ok_pregunta)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton_respuesta = QtWidgets.QPushButton(self.widget)
        self.boton_respuesta.setObjectName("boton_respuesta")
        self.horizontalLayout_2.addWidget(self.boton_respuesta)
        self.ok_respuesta = QtWidgets.QPushButton(self.widget)
        self.ok_respuesta.setObjectName("ok_respuesta")
        self.horizontalLayout_2.addWidget(self.ok_respuesta)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_pregunta.setText(_translate("MainWindow", "pregunta"))
        self.ok_pregunta.setText(_translate("MainWindow", "ok"))
        self.boton_respuesta.setText(_translate("MainWindow", "respuesta"))
        self.ok_respuesta.setText(_translate("MainWindow", "ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
