# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(491, 409)
        font = QtGui.QFont()
        font.setPointSize(3)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(8, 5, 166, 270))
        self.label.setStyleSheet("background-color:rgb(83, 83, 83);\n"
"border-radius: 10%;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.question_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_button.sizePolicy().hasHeightForWidth())
        self.question_button.setSizePolicy(sizePolicy)
        self.question_button.setMaximumSize(QtCore.QSize(10000, 30000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.question_button.setFont(font)
        self.question_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.question_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"}")
        self.question_button.setObjectName("question_button")
        self.verticalLayout.addWidget(self.question_button)
        self.answer_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_button.sizePolicy().hasHeightForWidth())
        self.answer_button.setSizePolicy(sizePolicy)
        self.answer_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.answer_button.setFont(font)
        self.answer_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.answer_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgba(80, 80, 80, 80);\n"
"\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(210, 210, 210);\n"
"    color: rgbrgb(99, 99, 99);\n"
"\n"
"}")
        self.answer_button.setObjectName("answer_button")
        self.verticalLayout.addWidget(self.answer_button)
        self.undo_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undo_button.sizePolicy().hasHeightForWidth())
        self.undo_button.setSizePolicy(sizePolicy)
        self.undo_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.undo_button.setFont(font)
        self.undo_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.undo_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(85, 170, 127);\n"
"}\n"
"")
        self.undo_button.setObjectName("undo_button")
        self.verticalLayout.addWidget(self.undo_button)
        self.toanky_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toanky_button.sizePolicy().hasHeightForWidth())
        self.toanky_button.setSizePolicy(sizePolicy)
        self.toanky_button.setMaximumSize(QtCore.QSize(10000, 3000))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toanky_button.setFont(font)
        self.toanky_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toanky_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(99, 99, 99);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:14%;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(110,110,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(255, 176, 17);\n"
"}\n"
"")
        self.toanky_button.setObjectName("toanky_button")
        self.verticalLayout.addWidget(self.toanky_button)
        self.answer_count_label = QtWidgets.QLabel(Form)
        self.answer_count_label.setGeometry(QtCore.QRect(155, 72, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_count_label.sizePolicy().hasHeightForWidth())
        self.answer_count_label.setSizePolicy(sizePolicy)
        self.answer_count_label.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.answer_count_label.setFont(font)
        self.answer_count_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius:10px;\n"
"color: rgb(255, 255, 255);")
        self.answer_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_count_label.setObjectName("answer_count_label")
        self.question_count_label = QtWidgets.QLabel(Form)
        self.question_count_label.setGeometry(QtCore.QRect(155, 5, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_count_label.sizePolicy().hasHeightForWidth())
        self.question_count_label.setSizePolicy(sizePolicy)
        self.question_count_label.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.question_count_label.setFont(font)
        self.question_count_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius:10px;\n"
"color: rgb(255, 255, 255);")
        self.question_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_count_label.setObjectName("question_count_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.question_button.setText(_translate("Form", "question"))
        self.answer_button.setText(_translate("Form", "answer"))
        self.undo_button.setText(_translate("Form", "undo"))
        self.toanky_button.setText(_translate("Form", "upload"))
        self.answer_count_label.setText(_translate("Form", "0"))
        self.question_count_label.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
